 pipeline{
    agent {label "jenkins-agent"}
    tools{
        nodejs 'node22'
    }
    environment{
        SCANNER_HOME=tool 'sonar-scanner'
        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
        AWS_ECR_REPO_NAME = credentials('ECR_REPO1')
        AWS_DEFAULT_REGION = 'ap-south-1'
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
    }
    stages {
        stage('cleanws')
        {
            steps{
                cleanWs()
            }
        }
        stage('Checkout git')
        {
            steps{
                    git branch: 'main', url: 'https://github.com/Rakshithrpoojary/mernauthapp.git'
            }
        }
        stage("install packages")
        {
            steps{
                dir("frontend")
                {
                sh "npm install"

                }
            }
        }
        stage("trivy scan")
        {
            steps{
                sh "trivy fs . > trivy.txt"
            }
        }
        stage("soanr scann")
        {
            steps{
                dir("frontend")
                {
                        withSonarQubeEnv('sonar-cred-main'){
                        sh ''' $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=mern-frontend \
                        -Dsonar.projectKey=mern-frontend '''
                        }
                }

            }
        }
        stage("Quality check")
        {
            steps{
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                }
            
        }
        stage("create docker image")
        {
          
                steps{
                      dir("frontend")
            {
                     sh 'docker system prune -f'
                            sh 'docker container prune -f'
                            sh 'docker build -t ${AWS_ECR_REPO_NAME} .'
                }
            }
        }
        stage("TRIVY Image Scan") {
            steps {
                sh 'trivy image ${AWS_ECR_REPO_NAME} > trivyimage.txt'
            }
        }
        stage("ECR Image Pushing") {
            steps {
                script {
                        sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}'
                        sh 'docker tag ${AWS_ECR_REPO_NAME} ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
                        sh 'docker push ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
                }
            }
        }

    }
}
